export const COUNTER_INCREMENT="COUNTER_INCREMENT";
export const COUNTER_DECREMENT="COUNTER_DECREMENT";

export const ADD_TODO="ADD_TODO";
export const COMPLETE_TODO="COMPLETE_TODO";
export const REMOVE_TODO="REMOVE_TODO";
export const UPDATE_TODO="UPDATE_TODO";

export const GET_TODO_REQUEST="GET_TODO_REQUEST";
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS";
export const GET_TODO_ERROR="GET_TODO_ERROR";


export const GET_SINGLE_TODO_REQUEST="GET_SINGLE_TODO_REQUEST";
export const GET_SINGLE_TODO_SUCCESS="GET_SINGLE_TODO_SUCCESS";
export const GET_SINGLE_TODO_ERROR="GET_SINGLE_TODO_ERROR";